# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output={GITHUB_WORKSPACE}/resume-brandon-beveridge.pdf -V fontsize=12pt -V geometry:margin=2cm -V mainfont="Noto Sans" ${GITHUB_WORKSPACE}/resume-brandon-beveridge.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated generated files on markdown change.
